[build]
command = "npm install && npm run build"
functions = "api/"
publish = "www"

[functions]
node_bundler = "esbuild"

[dev]
framework = "#custom"
command = "stencil build --dev --watch --serve"
port = 8888
targetPort = 3333
publish = "www"
autoLaunch = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
