/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface OrganismFooter {
    }
    interface OrganismHeader {
        "backHref": any;
    }
    interface OrganismMenu {
    }
    interface PageAbout {
    }
    interface PageHome {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLOrganismFooterElement extends Components.OrganismFooter, HTMLStencilElement {
    }
    var HTMLOrganismFooterElement: {
        prototype: HTMLOrganismFooterElement;
        new (): HTMLOrganismFooterElement;
    };
    interface HTMLOrganismHeaderElement extends Components.OrganismHeader, HTMLStencilElement {
    }
    var HTMLOrganismHeaderElement: {
        prototype: HTMLOrganismHeaderElement;
        new (): HTMLOrganismHeaderElement;
    };
    interface HTMLOrganismMenuElement extends Components.OrganismMenu, HTMLStencilElement {
    }
    var HTMLOrganismMenuElement: {
        prototype: HTMLOrganismMenuElement;
        new (): HTMLOrganismMenuElement;
    };
    interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {
    }
    var HTMLPageAboutElement: {
        prototype: HTMLPageAboutElement;
        new (): HTMLPageAboutElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "organism-footer": HTMLOrganismFooterElement;
        "organism-header": HTMLOrganismHeaderElement;
        "organism-menu": HTMLOrganismMenuElement;
        "page-about": HTMLPageAboutElement;
        "page-home": HTMLPageHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface OrganismFooter {
    }
    interface OrganismHeader {
        "backHref"?: any;
    }
    interface OrganismMenu {
    }
    interface PageAbout {
    }
    interface PageHome {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "organism-footer": OrganismFooter;
        "organism-header": OrganismHeader;
        "organism-menu": OrganismMenu;
        "page-about": PageAbout;
        "page-home": PageHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "organism-footer": LocalJSX.OrganismFooter & JSXBase.HTMLAttributes<HTMLOrganismFooterElement>;
            "organism-header": LocalJSX.OrganismHeader & JSXBase.HTMLAttributes<HTMLOrganismHeaderElement>;
            "organism-menu": LocalJSX.OrganismMenu & JSXBase.HTMLAttributes<HTMLOrganismMenuElement>;
            "page-about": LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
        }
    }
}
